CREATE TABLE  "ORDERS" 
   (
    "ORD_NUM" decimal(6,0) NOT NULL PRIMARY KEY, 
	"ORD_AMOUNT" decimal(12,2) NOT NULL, 
	"ADVANCE_AMOUNT" decimal(12,2) NOT NULL, 
	"ORD_DATE" DATE NOT NULL, 
	"CUST_CODE" nvarchar(6) NOT NULL REFERENCES CUSTOMER, 
	"AGENT_CODE" nvarchar(6) NOT NULL REFERENCES AGENTS, 
	"ORD_DESCRIPTION" nvarchar(60) NOT NULL
   );
